name: b2
base: core24
adopt-info: b2
summary: b2 BBC Micro Emulator
description: |
  A cross-platform BBC Micro emulator. Use your Linux PC to play your old
  BBC games or develop new BBC software..

grade: stable
confinement: strict


compression: lzo

layout:
#  /usr/share/drirc.d:
#    bind: $SNAP/usr/share/drirc.d
  /usr/lib/x86_64-linux-gnu/dri:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/dri
  /usr/share/vulkan:
    bind: $SNAP/usr/share/vulkan
  /usr/lib/x86_64-linux-gnu/libvulkan_intel.so:
    bind-file: $SNAP/usr/lib/x86_64-linux-gnu/libvulkan_intel.so
  /usr/lib/x86_64-linux-gnu/libvulkan_lvp.so:
    bind-file: $SNAP/usr/lib/x86_64-linux-gnu/libvulkan_lvp.so
  /usr/lib/x86_64-linux-gnu/libvulkan_radeon.so:
    bind-file: $SNAP/usr/lib/x86_64-linux-gnu/libvulkan_radeon.so

apps:
  b2:
    command: b2
    extensions: [gnome]
    environment:
      GTK_PATH: $SNAP/lib/gtk-2.0
      GTK_DATA_PREFIX: $SNAP
      XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS
      VK_ICD_FILENAMESr: /var/lib/snapd/lib/vulkan/icd.d/nvidia_icd.json:$SNAP/usr/share/vulkan/icd.d/radeon_icd.x86_64.json:$SNAP/usr/share/vulkan/icd.d/intel_icd.x86_64.json
    plugs:
      - opengl
      - audio-playback
      - audio-record
      - home
      - x11
      - desktop
      - desktop-legacy
      - joystick
      - network
      - network-bind
      - removable-media
      - mount-observe

parts:
  libs:
    plugin: nil
    stage-packages:
      - libspeechd2
      - mesa-va-drivers
      - mesa-vulkan-drivers
      - vulkan-tools
    prime:
      - usr/lib/*/libspeech*
      - usr/lib/*/dri
      - usr/lib/*/libVk*
      - usr/lib/*/libvulkan*
      - usr/lib/*/libxcb-randr*
      - usr/share/vulkan
      - usr/bin/vk*
  b2:
    plugin: make
    source: https://github.com/tom-seddon/b2.git
    override-pull: |
      craftctl default
      head -n5 src/b2/misc.cpp
      # Insert #include <limits> to the top of the src/b2/misc.cpp file to fix build error
      sed -i '1i#include <limits>' src/b2/misc.cpp
      head -n5 src/b2/misc.cpp
    override-build: |
      set -x
      git submodule init
      git submodule update
      sed -i 's|RMT_ENABLED=1|RMT_ENABLED=0|g' submodules/CMakeLists.txt
      make init
      craftctl set version=$(git describe --tags | cut -d- -f2-4 )
      cd build/r.linux
      ninja
      cp ./src/b2/b2 $CRAFT_PART_INSTALL
      cp -a ./src/b2/assets $SNAPCRAFT_PART_INSTALL
      mkdir -p $CRAFT_PART_INSTALL/lib/gtk-2.0
      mkdir -p $CRAFT_PART_INSTALL/share/themes
      mkdir -p $CRAFT_PART_INSTALL/share/icons
    build-snaps:
      - cmake/latest/stable
    build-environment:
      - PATH: /snap/bin:$PATH
    stage-packages:
      - libuv1
      - libglx-mesa0
      # - libbrotli1
      # - libcaca0
      # - libtheora0
      - libgssapi-krb5-2
      - libicu74
      - libsphinxbase3
      # - libmfx1
      - libcurl4
      # - ffmpeg
      - libasn1-8-heimdal
      - libatk1.0-0
      # - libbrotli1
      - libcurl3-gnutls
      - libdatrie1
      - libgdk-pixbuf2.0-0
      # - libgssapi3-heimdal
      - libgtk2.0-0
      - libhcrypto5t64-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libkrb5-26-heimdal
      - libldap2
      - libnghttp2-14
      - libopengl0
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpsl5
      - libroken19t64-heimdal
      - librtmp1
      - libsasl2-2
      - libssh-4
      - libthai0
      - libwind0-heimdal
      - libxcomposite1
      - libfribidi0
      - libglx-mesa0
      # - mesa-va-drivers
      - libsdl2-2.0-0
    build-packages:
      - libcurl4-gnutls-dev
      - uuid-dev
      - libgtk2.0-dev
      - libgl1-mesa-dev
      - libpulse-dev
      - libgles2-mesa-dev
      - libx264-dev
      - ffmpeg
      - ninja-build
      - build-essential
      - libsdl2-dev
      - libsdl2-net-dev
      - libuv1-dev

