name: b2
base: core22
adopt-info: b2
summary: b2 BBC Micro Emulator
description: |
  A cross-platform BBC Micro emulator. Use your Linux PC to play your old 
  BBC games or develop new BBC software..

grade: stable
confinement: strict

architectures:
  - build-on: amd64

compression: lzo

assumes:
  - snapd2.55.4

plugs:
  gaming-mesa:
    interface: content
    target: $SNAP/graphics
    default-provider: gaming-graphics-core22

layout:
  # https://discourse.ubuntu.com/t/the-graphics-core20-snap-interface/23000
  /usr/share/libdrm:
    bind: $SNAP/graphics/usr/share/libdrm
  /usr/share/drirc.d:
    bind: $SNAP/graphics/usr/share/drirc.d
  /usr/share/glvnd/egl_vendor.d:
    bind: $SNAP/graphics/usr/share/glvnd/egl_vendor.d
  /usr/lib/x86_64-linux-gnu/alsa-lib:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/alsa-lib
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /usr/share/X11/xkb:
    bind: $SNAP/usr/share/X11/xkb
  /usr/lib/x86_64-linux-gnu/libvulkan_intel.so:
    symlink: $SNAP/graphics/usr/lib/x86_64-linux-gnu/libvulkan_intel.so
  /usr/lib/i386-linux-gnu/libvulkan_intel.so:
    symlink: $SNAP/graphics/usr/lib/i386-linux-gnu/libvulkan_intel.so
  /usr/lib/x86_64-linux-gnu/libvulkan_lvp.so:
    symlink: $SNAP/graphics/usr/lib/x86_64-linux-gnu/libvulkan_lvp.so
  /usr/lib/i386-linux-gnu/libvulkan_lvp.so:
    symlink: $SNAP/graphics/usr/lib/i386-linux-gnu/libvulkan_lvp.so
  /usr/lib/x86_64-linux-gnu/libvulkan_radeon.so:
    symlink: $SNAP/graphics/usr/lib/x86_64-linux-gnu/libvulkan_radeon.so
  /usr/lib/i386-linux-gnu/libvulkan_radeon.so:
    symlink: $SNAP/graphics/usr/lib/i386-linux-gnu/libvulkan_radeon.so
  /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0.0.0:
    symlink: $SNAP/graphics/usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0.0.0
  /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0:
    symlink: $SNAP/graphics/usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0.0.0
  /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0:
    symlink: $SNAP/graphics/usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
  /usr/lib/x86_64-linux-gnu/libxcb.so:
    symlink: $SNAP/graphics/usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
  /usr/lib/x86_64-linux-gnu/libxcb.so.1:
    symlink: $SNAP/graphics/usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
  /etc/ld.so.cache:
    bind-file: $SNAP_DATA/etc/ld.so.cache
  /etc/fonts:
    bind: $SNAP/etc/fonts

environment:
  LD_LIBRARY_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/pulseaudio:$SNAP/graphics/lib/i386-linux-gnu:$SNAP/graphics/usr/lib:$SNAP/usr/lib/i386-linux-gnu:$SNAP/lib/i386-linux-gnu:$SNAP/usr/lib/i386-linux-gnu/pulseaudio${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
  LIBGL_DRIVERS_PATH: $SNAP/graphics/usr/lib/i386-linux-gnu/dri:$SNAP/graphics/usr/lib/x86_64-linux-gnu/dri:${LIBGL_DRIVERS_PATH:+:$LIBGL_DRIVERS_PATH}

apps:
  b2:
    command: b2
    extensions: [gnome]
    environment:
      GTK_PATH: $SNAP/lib/gtk-2.0
      GTK_DATA_PREFIX: $SNAP
      XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS
    plugs:
      - opengl
      - audio-playback
      - audio-record
      - home
      - x11
      - desktop
      - desktop-legacy
      - joystick
      - network
      - network-bind
      - removable-media
      - mount-observe

parts:
  # snapcraft-preload:
  #   source: https://github.com/sergiusens/snapcraft-preload.git
  #   plugin: cmake
  #   build-environment:
  #     - PATH: /snap/bin:$PATH
  #   build-snaps:
  #     - cmake/latest/stable
  #   stage-packages:
  #     - on amd64:
  #       - lib32stdc++6
  #   build-packages:
  #     - on amd64:
  #       - gcc-multilib
  #       - g++-multilib 
  b2:
    plugin: make
    source: https://github.com/tom-seddon/b2.git
    override-build: |
      set -x
      git submodule init
      git submodule update
      sed -i 's|RMT_ENABLED=1|RMT_ENABLED=0|g' submodules/CMakeLists.txt
      make init
      snapcraftctl set-version "$(git describe --tags | cut -d- -f2-4 )"
      cd build/r.linux
      ninja
      cp ./src/b2/b2 $SNAPCRAFT_PART_INSTALL
      cp -a ./src/b2/assets $SNAPCRAFT_PART_INSTALL
      mkdir -p $SNAPCRAFT_PART_INSTALL/lib/gtk-2.0
      mkdir -p $SNAPCRAFT_PART_INSTALL/share/themes
      mkdir -p $SNAPCRAFT_PART_INSTALL/share/icons
    build-snaps:
      - cmake/latest/stable
    build-environment:
      - PATH: /snap/bin:$PATH 
    stage-packages:
      - libuv1
      - libglx-mesa0
      # - libbrotli1
      # - libcaca0
      # - libtheora0
      - libgssapi-krb5-2
      - libicu70
      - libsphinxbase3
      # - libmfx1
      - libcurl4
      # - ffmpeg
      - libasn1-8-heimdal
      - libatk1.0-0
      # - libbrotli1
      - libcurl3-gnutls
      - libdatrie1
      - libgdk-pixbuf2.0-0
      # - libgssapi3-heimdal
      - libgtk2.0-0
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libkrb5-26-heimdal
      - libldap-2.5-0
      - libnghttp2-14
      - libopengl0
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpsl5
      - libroken18-heimdal
      - librtmp1
      - libsasl2-2
      - libssh-4
      - libthai0
      - libwind0-heimdal
      - libxcomposite1
      - libfribidi0
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      # - mesa-va-drivers
      - libsdl2-2.0-0
    build-packages:
      - libcurl4-gnutls-dev
      - uuid-dev
      - libgtk2.0-dev
      - libgl1-mesa-dev
      - libpulse-dev
      - libgles2-mesa-dev
      - libx264-dev
      - ffmpeg
      - ninja-build
      - build-essential
      - libsdl2-dev
      - libsdl2-net-dev
      - libuv1-dev


  cleanup:
    after: [b2]
    plugin: nil
    build-snaps:
      - gaming-graphics-core22/kisak-fresh/candidate
    override-prime: |
      set -eux
      cd /snap/gaming-graphics-core22/current/usr/lib
      find . -type f,l -exec rm -f $CRAFT_PRIME/usr/lib/{} \;
      cd /snap/gaming-graphics-core22/current/usr/share
      find . -type f,l -exec rm -f $CRAFT_PRIME/usr/share/{} \;