name: b2
base: core20
adopt-info: b2
summary: b2 BBC Micro Emulator
description: |
  A cross-platform BBC Micro emulator. Use your Linux PC to play your old 
  BBC games or develop new BBC software..

grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  b2:
    command: b2
    extensions: [gnome-3-38]
    environment:
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$LD_LIBRARY_PATH"
      GTK_PATH: $SNAP/lib/gtk-2.0
      GTK_DATA_PREFIX: $SNAP
      XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS
    plugs:
      - opengl
      - audio-playback
      - audio-record
      - home
      - x11
      - desktop
      - desktop-legacy
      - joystick
      - network
      - network-bind
      - removable-media
      - mount-observe

parts:
  # snapcraft-preload:
  #   source: https://github.com/sergiusens/snapcraft-preload.git
  #   plugin: cmake
  #   build-environment:
  #     - PATH: /snap/bin:$PATH
  #   build-snaps:
  #     - cmake/latest/stable
  #   stage-packages:
  #     - on amd64:
  #       - lib32stdc++6
  #   build-packages:
  #     - on amd64:
  #       - gcc-multilib
  #       - g++-multilib 
  b2:
    plugin: make
    source: https://github.com/tom-seddon/b2.git
    override-build: |
      set -x
      git submodule init
      git submodule update
      sed -i 's|RMT_ENABLED=1|RMT_ENABLED=0|g' submodules/CMakeLists.txt
      make init
      snapcraftctl set-version "$(git describe --tags | cut -d- -f2-4 )"
      cd build/r.linux
      ninja
      cp ./src/b2/b2 $SNAPCRAFT_PART_INSTALL
      cp -a ./src/b2/assets $SNAPCRAFT_PART_INSTALL
      mkdir -p $SNAPCRAFT_PART_INSTALL/lib/gtk-2.0
      mkdir -p $SNAPCRAFT_PART_INSTALL/share/themes
      mkdir -p $SNAPCRAFT_PART_INSTALL/share/icons
    build-snaps:
      - cmake/latest/stable
    build-environment:
      - PATH: /snap/bin:$PATH 
    stage-packages:
      - ffmpeg
      - libasn1-8-heimdal
      - libatk1.0-0
      - libbrotli1
      - libcurl3-gnutls
      - libdatrie1
      - libgdk-pixbuf2.0-0
      - libgssapi3-heimdal
      - libgtk2.0-0
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - libnghttp2-14
      - libopengl0
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpsl5
      - libroken18-heimdal
      - librtmp1
      - libsasl2-2
      - libssh-4
      - libthai0
      - libwind0-heimdal
      - libxcomposite1
      - libfribidi0
      - libgl1-mesa-dri
      - libgl1-mesa-glx
    build-packages:
      - libcurl4-gnutls-dev
      - uuid-dev
      - libgtk2.0-dev
      - libgl1-mesa-dev
      - libpulse-dev
      - libgles2-mesa-dev
      - libx264-dev
      - ffmpeg
      - ninja-build
      - build-essential

